//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shahid_Bhai.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MondayDropEntities1 : DbContext
    {
        public MondayDropEntities1()
            : base("name=MondayDropEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTb> CategoryTbs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GendrTb> GendrTbs { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
    }
}
